### PR TITLE
Used yield to be lazy

### PR DESCRIPTION
**Pull request by stekycz**

### CODE REVIEW

**Comment by matej21** [comment]
Failing on:
```php
$order = new Order(['orderItems' => [
	['id' => 1],
	['id' => 2],
]]);

$orderEntry = EntryViewer::viewEntry($order, function (Order $order) {
	return [
		'orderItems' => EntryViewer::viewEntries($order->orderItems, function (OrderItem $item) {
			return ['id' => $item->id];
		}),
	];
});

foreach ($orderEntry->orderItems as $item) {
}
foreach ($orderEntry->orderItems as $item) {
}
```

```
Fatal error: Uncaught Exception: Cannot traverse an already closed generator
```

**Comment by matej21** [comment]
Also, generator does not support `count()`

**Comment by Tharos** [comment]
Thank you both for your contribution!

I like an idea of using generators but as @matej21 noticed, there are some issues with them. Especially troubles with count are very annoying for me.

That's why I tend to preserve current implementation at this moment. You can easily wrap some collection with generator when making sense.

Maybe we could introduce interface for collection and you could optionally set which collection class should be used when instantiating entry. I mean what class should be instantiated here: https://github.com/Tharos/Schematic/blob/master/src/Schematic/Entry.php#L55

**Comment by Tharos** [comment]
Hmm, @matej21... Are you sure there is an issue with count? :)

`Countable` is implemented by `Entries` and `count` is based on `Entries::$data`. No generator is needed to count entries. Isn't it?

**Comment by matej21** [comment]
@Tharos the problem isn't with the Entries, but with the generator returned by viewEntries. it always returns 1 https://3v4l.org/QOJW9

**Comment by Tharos** [comment]
Oh yes, now I understand.

**Comment by Tharos** [comment]
Closing for inactivity.

This branch should solve similar issue: https://github.com/Tharos/Schematic/commit/e6a8832e612c783a98db1424a59f3c7013322b72

**Pull request closed without merging**
